# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'command_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Other_Win2(object):
    def setupUi(self, Other_Win2):
        Other_Win2.setObjectName("Other_Win2")
        Other_Win2.resize(391, 520)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("micro_img.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Other_Win2.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Other_Win2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 220, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 260, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 300, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        Other_Win2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Other_Win2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        Other_Win2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Other_Win2)
        self.statusbar.setObjectName("statusbar")
        Other_Win2.setStatusBar(self.statusbar)

        self.retranslateUi(Other_Win2)
        QtCore.QMetaObject.connectSlotsByName(Other_Win2)

    def retranslateUi(self, Other_Win2):
        _translate = QtCore.QCoreApplication.translate
        Other_Win2.setWindowTitle(_translate("Other_Win2", "Друг v1.0"))
        self.label.setText(_translate("Other_Win2", "Список команд голосового помощника"))
        self.label_2.setText(_translate("Other_Win2", "\'привет\' - приветствие"))
        self.label_3.setText(_translate("Other_Win2", "\'погода\' - узнать температуру в городе"))
        self.label_4.setText(_translate("Other_Win2", "\'как тебя зовут\' - узнать имя помощника"))
        self.label_5.setText(_translate("Other_Win2", "\'браузер\' - открыть браузер"))
        self.label_6.setText(_translate("Other_Win2", "\'новости\' - открыть новостной портал"))
        self.label_7.setText(_translate("Other_Win2", "\'время\' - показать текущее время на устройстве"))
        self.label_8.setText(_translate("Other_Win2", "\'доллар\' - курс доллара на текущий момент"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Other_Win2 = QtWidgets.QMainWindow()
    ui = Ui_Other_Win2()
    ui.setupUi(Other_Win2)
    Other_Win2.show()
    sys.exit(app.exec_())
